account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    # post views
    path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.my_recipes, name='my_recipes'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

recipes/urls.py
from django.urls import path
from . import views


app_name = 'recipes'

urlpatterns = [
    path('create/', views.recipe_create, name='create'),
    path('detail/<int:id>/<slug:slug>', views.recipe_detail, name='detail'),
    path('', views.recipe_list, name='list'),
    path('update/<int:id>/', views.recipe_update, name='update'),
    path('delete/<int:id>/', views.recipe_delete, name='delete'),
]

yummyapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('recipes/', include('recipes.urls', namespace='recipes')),
]

recipes/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


class Recipe(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='recipes_created', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    ingredients = models.TextField(blank=True)
    steps = models.TextField(blank=True)
    duration = models.TextField(blank=True)
    servings = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='recipes_liked',
                                        blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('recipes:detail', args=[self.id, self.slug])

account/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

recipes/forms.py
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify
from django import forms
from .models import Recipe


class RecipeCreateForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'ingredients', 'steps', 'duration', 'servings')
        # widgets = {'url': forms.HiddenInput,}

account/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm
from django.contrib.auth.decorators import login_required


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})


@login_required
def my_recipes(request):
    return render(request, 'account/my_recipes.html', {'section': 'my_recipes'})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request, 'account/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form})

recipes/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RecipeCreateForm
from .models import Recipe
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
def recipe_create(request):
    if request.method == 'POST':
        # form is sent
        form = RecipeCreateForm(data=request.POST)
        if form.is_valid():
            # form data is valid
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            # assign current user to the item
            new_item.user = request.user
            new_item.save()
            messages.success(request, 'Recipe added successfully')
            # redirect to new created item detail view
            return HttpResponseRedirect(reverse('recipes:list'))
    else:
        # build form with data provided by the bookmarklet via GET
        form = RecipeCreateForm(data=request.GET)
        return render(request, 'recipes/recipe/create.html', {'section': 'recipes', 'form': form})


def recipe_detail(request, id, slug):
    recipe = get_object_or_404(Recipe, id=id, slug=slug)
    return render(request, 'recipes/recipe/detail.html', {'section': 'recipes', 'recipe': recipe})


@login_required
def recipe_list(request):
    recipes = Recipe.objects.all()
    paginator = Paginator(recipes, 8)
    page = request.GET.get('page')
    try:
        recipes = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        recipes = paginator.page(1)
    except EmptyPage:
        recipes = paginator.page(paginator.num_pages)
    return render(request, 'recipes/recipe/list.html', {'section': 'recipes', 'recipes': recipes})


def recipe_update(request, id):
    recipe = Recipe.objects.get(id=id)
    form = RecipeCreateForm(instance=recipe)
    if request.method == 'POST':
        form = RecipeCreateForm(data=request.POST, instance=recipe)
        if form.is_valid():
            form.save()
            #return recipe_list(request)
            return HttpResponseRedirect(reverse('recipes:list'))
    context = {'form': form}
    return render(request, 'recipes/recipe/update.html', context)


def recipe_delete(request, id):
    recipe = Recipe.objects.get(id=id)
    if request.method == 'POST':
        recipe.delete()
        return HttpResponseRedirect(reverse('recipes:list'))
    context = {'recipe': recipe}
    return render(request, 'recipes/recipe/delete.html', context)

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="header">
            <span class="logo">Yummy</span>
            {% if request.user.is_authenticated %}
                <ul class="menu">
                    <li {% if section == 'my_recipes' %}class='selected'{% endif %}>
                        <a href='{% url 'my_recipes' %}'>Home</a>
                    </li>
                    <li {% if section == 'Recipes' %}class='selected'{% endif %}>
                        <a href='{% url 'recipes:list' %}'>Recipes</a>
                    </li>
                </ul>
            {% endif %}
            <span class="user">
            {% if request.user.is_authenticated %}
                Hello {{ request.user.username }},
                <a href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'login' %}">Log-in</a>
            {% endif %}
            </span>
        </div>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

recipes/templates/recipes/recipe/create.html
{% extends "base.html" %}
{% block title %}Create Recipe{% endblock %}
{% block content %}
    <h1>Create Recipe</h1>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Save">
    </form>
{% endblock %}

recipes/templates/recipes/recipe/delete.html
{% extends "base.html" %}
{% block title %}Delete Recipe{% endblock %}
{% block content %}
<h1>Delete Recipe</h1>
<p>Are You Sure You Want To Delete "{{recipe}}"</p>
<form method="POST">
    {% csrf_token %}
    <a href="{% url 'recipes:list' %}">Cancel</a>
    <input type="submit" name="Confirm">
</form>
{% endblock %}

recipes/templates/recipes/recipe/detail.html
{% extends "base.html" %}
{% block title %}{{ image.title }}{% endblock %}
{% block content %}
    <h1>{{ recipe.title }}</h1>
    {% with total_likes=recipe.users_like.count %}
        <div class="recipe-info">
            <a href="{% url 'recipes:update' recipe.id %}">Update</a>
            <br>
            Ingredients:
            {{ recipe.ingredients|linebreaks }}
            Steps:
            {{ recipe.steps|linebreaks }}
            Duration:
            {{ recipe.duration|linebreaks }}
            Servings:
            {{ recipe.servings|linebreaks }}
            <br>
            <div>
                <span class="count">
                {{ total_likes }} like{{ total_likes|pluralize }}
                </span>
            </div>
        </div>
        <br>
        <div class="recipe-likes">
        {% for user in recipe.users_like.all %}
            <div>
            <p>{{ user.username }}</p>
            </div>
            {% empty %}
            Nobody likes this recipe yet.
        {% endfor %}
        </div>
    {% endwith %}
{% endblock %}

recipes/templates/recipes/recipe/list.html
{% extends "base.html" %}
{% block title %}Recipes{% endblock %}
{% block content %}
<h1>Recipes</h1>
<div id="recipe-list">
    {% for recipe in recipes %}
    <div class="recipe">
        <div class="info">
        <a href="{{ recipe.get_absolute_url }}" class="title">
        {{ recipe.title }}
        </a>
        <a href=" {% url 'recipes:update' recipe.id %}">Update</a>
        <a href=" {% url 'recipes:delete' recipe.id %}">Delete</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

recipes/templates/recipes/recipe/update.html
{% extends "base.html" %}
{% block title %}Recipes{% endblock %}
{% block content %}
<h1>Update Recipe</h1>
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        <!-- form as paragraph -->
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

</div>
{% endblock %}